baseurl = "https://strangfeld.io"
title = "Strangfeld I/O"

theme = "github.com/luizdepra/hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
enableEmoji = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
    author = "Marvin Strangfeld"
    description = "Strangfeld I/O"
    keywords = "strangfeld,marvin,blog,developer,personal,sre,devops,open,source,git,github,go,kotlin,gradle,docker,kubernetes"
    info = "Open Source | Software Engineering | DevOps and SRE"
    avatarurl = "img/profile.jpg"
    footercontent = "“We’re all stories, in the end. Just make it a good one, eh?” ~ The Doctor"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    commit = "https://github.com/mstrangfeld/blog/tree/"

    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/mstrangfeld/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/strangfeld_io/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/marvin-strangfeld/"
[[params.social]]
    name = "StackOverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/12398541/marvin-strangfeld"
[[params.social]]
    name = "Mastodon"
    icon = "fab fa-mastodon"
    weight = 4
    url = "https://mastodon.social/@strangfeld"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 6
    url = "https://strangfeld.io/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Tags"
            weight = 3
            url = "tags/"